### ISSUE TITLE
ImportError: cannot import name 'model_fuctions' from 'models' (unknown location)

### ISSUE THREAD

**Issue by xixihahalsr** [liyaooi/FETCH#1]
Can I ask a favor?

The code occurs the error :          FETCH-main\feature_engineer\attention_searching\training_ops.py", line 12, in <module>
                                                     from models import model_fuctions
                                                     ImportError: cannot import name 'model_fuctions' from 'models' (unknown location)

and I don't find the "model_fuctions" file from the folder  'models'

**Comment by liyaooi** [comment]
Hi,

Thank you for bringing this issue to my attention. I apologize for the delayed response and any inconvenience caused by the missing file. I want to assure you that I have fixed the problem and the code is now running smoothly as expected.

Your feedback is greatly appreciated, and I am grateful for your understanding and patience. If you encounter any further issues or have any additional questions, please don't hesitate to let me know. I'm here to help!
