### ISSUE TITLE
How does the input layer work and what is the meaning of the attention layer?

### ISSUE THREAD

**Issue by HBhswl** [liyaooi/FETCH#2]
Hello, 

I am confused about the following code. I wonder what the meaning of `//8`, `//4` is and how they are specified to these values.
``` python
    arithmetic = OPS["arithmetic"]
    value_convert_c = OPS["value_convert"] * max(1, n_features_c // 8) + max(1, n_features_c // 4) * OPS["special_ops"]
    special_ops = max(1, (n_features_c + n_features_d) // 12) * OPS["special_ops"]
```

And another problem is that  **a fully connected network containing an input layer and dense layer, It changes the dimension of a variable-length feature vector to a fixed length**.  It seems that you transpose the tabular data and regard the `features(e.g., A, B, C, D)` as the batch dimension and regard the samples as the feature dimension, so that the dimension of the input layer is equal to the num of the data. 
``` python
    self.reduction_dimension = ReductionDimension(data_nums, d_model)
```
If so, I am confused about the meanings of the attention layer, one sample attend to another sample? And how can I choose one variable `(e.g., A)` to conduct an action `(e.g., +B)` as `(A, B)` are even not in the same batch?

**Comment by liyaooi** [comment]
> Hello,
> 
> I am confused about the following code. I wonder what the meaning of `//8`, `//4` is and how they are specified to these values.
> 
> ```python
>     arithmetic = OPS["arithmetic"]
>     value_convert_c = OPS["value_convert"] * max(1, n_features_c // 8) + max(1, n_features_c // 4) * OPS["special_ops"]
>     special_ops = max(1, (n_features_c + n_features_d) // 12) * OPS["special_ops"]
> ```
> 
> And another problem is that **a fully connected network containing an input layer and dense layer, It changes the dimension of a variable-length feature vector to a fixed length**. It seems that you transpose the tabular data and regard the `features(e.g., A, B, C, D)` as the batch dimension and regard the samples as the feature dimension, so that the dimension of the input layer is equal to the num of the data.
> 
> ```python
>     self.reduction_dimension = ReductionDimension(data_nums, d_model)
> ```
> 
> If so, I am confused about the meanings of the attention layer, one sample attend to another sample? And how can I choose one variable `(e.g., A)` to conduct an action `(e.g., +B)` as `(A, B)` are even not in the same batch?

Thank you for the thoughtful questions on the code. Apologies for the late response. Let me try to clarify:

1. We designed the architecture to treat all operators with equal weight initially, rather than cascading and learning different weights like some other methods. As a rough approximation to increase the sampling weight for certain operators, we duplicated some operators using ``n_features_c // 8`` and ``n_features_c // 4``  While preset weights isn't the most elegant approach, we found it was an effective hyperparameter after some experiments.

2. If you look closely at our code, you'll see we input the entire table as ONE batch to the ``Actor`` network together, so all column information appears concurrently in the attention layer. Additionally, since our final operations are on columns, getting good column representations was critical. Transposing features into the batch dimension helped the network encode useful column embeddings.
